pipeline:
  build:
    image: alpine
    commands:
      #- export MYNAME=$NAME
      #- echo $${MYNAME}
      - apk update
      - apk add py-pip
      - pip install awscli
      - aws s3 ls
    secrets: [ NAME ]
