pipeline:
  build_push:
    image: alpine
    commands:
      - env
    when:
      event: push
      branch: [feature/*, dev]

  build_pr:
    image: alpine
    commands:
      - env
    when:
      event: pull_request
      branch: [dev]
