---
pipeline:
  step1:
    image: alpine
    secrets: [ NAME ]
    commands:
      - env
    #cmd:i
    #  - testing
    #  - sandeep
  #step2:
  #  image: alpine
  #  commands:
  #    - echo step 2
    #when:
    #  status: [ success ]
