---
pipeline:
  step1:
    image: drone-plugin
    secrets: [ NAME ]
    commands:
      - env $${NAME}
    #cmd:
    #  - testing
    #  - sandeep
  #step2:
  #  image: alpine
  #  commands:
  #    - echo step 2
    #when:
    #  status: [ success ]
