pipeline:
  makezip:
    image: alpine
    commands:
      - apk update
      - apk add zip
      - zip cargill-${DRONE_BUILD_NUMBER}.zip cargill.py

  s3publish:
    image: plugins/s3
    region: ap-south-1
    bucket: my-sandeep-state
    source: cargill-${DRONE_BUILD_NUMBER}.zip
    target: /

  deploylambda:
    image: omerxx/drone-lambda-plugin
    function_name: drone
    s3_bucket: my-sandeep-state
    file_name: cargill-${DRONE_BUILD_NUMBER}.zip
    secrets: [ aws_default_region ]
