pipeline:
  #makezip:
  #  image: alpine
  #  commands:
  #    - apk update
  #    - apk add zip
  #    - zip cargill-${DRONE_BUILD_NUMBER}.zip cargill.py

  s3publish:
    image: alpineaws
    #region: $${AWS_REGION}
    bucket: my-sandeep-state
    #source: cargill-${DRONE_BUILD_NUMBER}.zip
    source: cargill.py
    #target: cargill-${DRONE_BUILD_NUMBER}.zip
    target: cargill.py
    when:
      event: deployment
      environment: production
    #secrets: [ AWS_DEFAULT_REGION ]

  #deploylambda:
  #  image: omerxx/drone-lambda-plugin
  #  function_name: drone
  #  s3_bucket: my-sandeep-state
  #  file_name: cargill-${DRONE_BUILD_NUMBER}.zip
    #aws_default_region: ap-south-1
  #  secrets: [ AWS_DEFAULT_REGION ]
